### ISSUE TITLE
"Key "size" for array with keys "theme, type" does not exist in in EWZRecaptchaBundle:Form:ewz_recaptcha_widget.html.twig

### ISSUE THREAD

**Issue by edgework** [excelwebzone/EWZRecaptchaBundle#103]
This commit broke the bundle

https://github.com/excelwebzone/EWZRecaptchaBundle/commit/05dfd72391c7d0d7453d9fd4e7489beed5432710

Getting the error "Key "size" for array with keys "theme, type" does not exist in in EWZRecaptchaBundle:Form:ewz_recaptcha_widget.html.twig at line 10"

**Comment by edgework** [comment]
Found the problem. Bad composer update.  Move along, nothing to see here.

**Comment by Gerben321** [comment]
Bad composer update? Could you elaborate? Getting the same on Symfony 3.4.

**Comment by romaricdrigon** [comment]
I got the same issue minutes ago, in my case, it was because `size` option was not defined. I set it to `normal` and it works fine.
Having no size was somehow tolerated in (very) old versions of the bundle, now I would guess you need to define `theme`, `size` and `type` options if you redefine `options`.
