### ISSUE TITLE
Change language dynamically

### ISSUE THREAD

**Issue by youssef06** [excelwebzone/EWZRecaptchaBundle#89]
Hi, i have a website that works in 2 languages, is it possible to set language dyanmically instead of it being hardcoded in config?

## Update
I found a solution, here is what i did:

1. Add custom RecaptchaType In config parameters (config.yml)
```
parameters:
    ewz_recaptcha.form.type.class: My\NameBundle\Form\RecaptchaType
```
2. Inherit from the bundle's RecaptchaType and Redefine buildView method:

```
namespace My\NameBundle\Form;

use EWZ\Bundle\RecaptchaBundle\Form\Type\RecaptchaType as BaseRecaptchaType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

/**
 * Class RecaptchaType
 * @package My\NameBundle\Form
 */
class RecaptchaType extends BaseRecaptchaType {

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $this->language = isset($view->vars['attr']['language']) ? $view->vars['attr']['language'] : $this->language;
        parent::buildView($view, $form, $options);
    }
}
```

3. Finally when building your form add language to the passed attributes:

```
$builder->add('recaptcha', EWZRecaptchaType::class, array(
        'attr' => array(
           'language' => $Your_Dynamically_Detected_Language
            'options' => array(
                'theme' => 'light',
                'type'  => 'image'
            )
        )
    ));
```

**Comment by webdiver** [comment]
I like the idea, since I am looking for a solution for that problem.

BUT, I can't get this to work.

`use EWZ\Bundle\RecaptchaBundle\Form\Type\RecaptchaType as BaseRecaptchaType;
`
.. that class does not exist, I use instead:
`use EWZ\Bundle\RecaptchaBundle\Form\Type\EWZRecaptchaType as BaseRecaptchaType;
`

But nothing happens, still shown in default_locale (de).

Any suggestions? Or better solutions for that need?

Thanks in advance!

**Comment by nocive** [comment]
bump :+1:
